# pandas dataframe and series

Pandas is a powerful data manipulation library in Python, widely used for data analysis and data cleaning. It provides two primary data structures: Series and DataFrame. A Series is a one-dimensional array-like object, while a DataFrame is a two-dimensional, size-mutable, and potentially heterogeneous tabular data structure with labeled axes (rows and columns).

In [2]:
!pip install pandas

Requirement already satisfied: pandas in c:\users\mayan\onedrive\documents\github\udemy_ml\venv\lib\site-packages (2.3.2)
Requirement already satisfied: numpy>=1.22.4 in c:\users\mayan\onedrive\documents\github\udemy_ml\venv\lib\site-packages (from pandas) (2.2.6)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\mayan\onedrive\documents\github\udemy_ml\venv\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\mayan\onedrive\documents\github\udemy_ml\venv\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\mayan\onedrive\documents\github\udemy_ml\venv\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\mayan\onedrive\documents\github\udemy_ml\venv\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [3]:
import pandas as pd

In [4]:
## series
# pandas series is a 1d array like object that can hold any data type. It is similar to a column in a table.

In [5]:
data = [1,2,3,4,5]
series = pd.Series(data)
print("Series\n",series)
print(type(series))

Series
 0    1
1    2
2    3
3    4
4    5
dtype: int64
<class 'pandas.core.series.Series'>

In [6]:
## series from dictionary

data = {'a': 1,'b': 2,'c': 3}
series_dict = pd.Series(data)
print(series_dict)

a    1
b    2
c    3
dtype: int64

In [7]:
data = [10,20,30]
index = ['a','b','c']
pd.Series(data,index = index)

a    10
b    20
c    30
dtype: int64

In [8]:
## data frame:
## create a dataframe from a dictionary of list

data = {
    "Name" : ['Krish','John','Jack'],
    'Age' : [25,30,45],
    'City' : ["Bangalore" , 'New York' , "Florida"]
}
df = pd.DataFrame(data)
print(df)
print(type(df))

    Name  Age       City
0  Krish   25  Bangalore
1   John   30   New York
2   Jack   45    Florida
<class 'pandas.core.frame.DataFrame'>

In [9]:
import numpy as np
df1 = np.array(df)
df1

array([['Krish', 25, 'Bangalore'],
       ['John', 30, 'New York'],
       ['Jack', 45, 'Florida']], dtype=object)

In [14]:
## create a dataframe from a list of dictionaries

data = [
    {"Name" : 'Krish','Age': 32 , "City" : "Bangalore"},
    {"Name" : 'John','Age': 30 , "City" : "manpada"},
    {"Name" : 'mayank','Age': 20 , "City" : "Bombay"},
    {"Name" : 'jackie','Age': 10 , "City" : "manpada"}
]

df = pd.DataFrame(data)
print(df)
print(type(df))

     Name  Age       City
0   Krish   32  Bangalore
1    John   30    manpada
2  mayank   20     Bombay
3  jackie   10    manpada
<class 'pandas.core.frame.DataFrame'>

In [12]:
df= pd.read_csv('sales_data.csv')
df.head()

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal
2,10003,2024-01-03,Clothing,Levi's 501 Jeans,3,69.99,209.97,Asia,Debit Card
3,10004,2024-01-04,Books,The Da Vinci Code,4,15.99,63.96,North America,Credit Card
4,10005,2024-01-05,Beauty Products,Neutrogena Skincare Set,1,89.99,89.99,Europe,PayPal

In [13]:
df.tail(5)

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
235,10236,2024-08-23,Home Appliances,Nespresso Vertuo Next Coffee and Espresso Maker,1,159.99,159.99,Europe,PayPal
236,10237,2024-08-24,Clothing,Nike Air Force 1 Sneakers,3,90.00,270.00,Asia,Debit Card
237,10238,2024-08-25,Books,The Handmaid's Tale by Margaret Atwood,3,10.99,32.97,North America,Credit Card
238,10239,2024-08-26,Beauty Products,Sunday Riley Luna Sleeping Night Oil,1,55.00,55.00,Europe,PayPal
239,10240,2024-08-27,Sports,Yeti Rambler 20 oz Tumbler,2,29.99,59.98,Asia,Credit Card

In [15]:
### accessing data from dataframe
df

     Name  Age       City
0   Krish   32  Bangalore
1    John   30    manpada
2  mayank   20     Bombay
3  jackie   10    manpada

In [16]:
df['Name']

0     Krish
1      John
2    mayank
3    jackie
Name: Name, dtype: object

In [18]:
type(df['Name'])

pandas.core.series.Series

In [20]:
df.loc[0] ## row index

Name        Krish
Age            32
City    Bangalore
Name: 0, dtype: object

In [21]:
df.iloc[0]

Name        Krish
Age            32
City    Bangalore
Name: 0, dtype: object

In [22]:
df.loc[0][0]

C:\Users\mayan\AppData\Local\Temp\ipykernel_5460\2527876973.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df.loc[0][0]

'Krish'

In [23]:
df.iloc[0][1]

C:\Users\mayan\AppData\Local\Temp\ipykernel_5460\2309508539.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df.iloc[0][1]

np.int64(32)

In [24]:
df.iloc[0][2]

C:\Users\mayan\AppData\Local\Temp\ipykernel_5460\2519637664.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df.iloc[0][2]

'Bangalore'

In [28]:
## accessing a specified elements

df.at[1,'Age']

np.int64(30)

In [29]:
df.at[2,'Name']

'mayank'

In [30]:
## accessing a specified element using iat

df.iat[2,2]

'Bombay'

In [31]:
### data manipulation with dataframe

df

     Name  Age       City
0   Krish   32  Bangalore
1    John   30    manpada
2  mayank   20     Bombay
3  jackie   10    manpada

In [38]:
## adding new column
df['Salary'] = [50000,60000,70000,10000]
df

     Name  Age       City  Salary
0   Krish   32  Bangalore   50000
1    John   30    manpada   60000
2  mayank   20     Bombay   70000
3  jackie   10    manpada   10000

In [ ]:
## remove a column
df.drop('Salary',axis = 1) ## by defaualt axis is 0 which means row , 1 : column

     Name  Age       City
0   Krish   32  Bangalore
1    John   30    manpada
2  mayank   20     Bombay
3  jackie   10    manpada

In [36]:
df

     Name  Age       City  Salary
0   Krish   32  Bangalore   50000
1    John   30    manpada   60000
2  mayank   20     Bombay   70000
3  jackie   10    manpada   10000

In [37]:
df = df.drop('Salary',axis = 1)
df

     Name  Age       City
0   Krish   32  Bangalore
1    John   30    manpada
2  mayank   20     Bombay
3  jackie   10    manpada

In [42]:
## anothe method to remove salary permnanently is inplace = true

df['Salary'] = [50000,60000,70000,10000]
df

     Name  Age       City  Salary
0   Krish   32  Bangalore   50000
1    John   30    manpada   60000
2  mayank   20     Bombay   70000
3  jackie   10    manpada   10000

In [44]:
df.drop('Salary',inplace = True,axis = 1)
df

     Name  Age       City
0   Krish   32  Bangalore
1    John   30    manpada
2  mayank   20     Bombay
3  jackie   10    manpada

In [45]:
## add age to the column
df['Age'] = df['Age'] + 1
df

     Name  Age       City
0   Krish   33  Bangalore
1    John   31    manpada
2  mayank   21     Bombay
3  jackie   11    manpada

In [46]:
df.drop(0)
df

     Name  Age       City
0   Krish   33  Bangalore
1    John   31    manpada
2  mayank   21     Bombay
3  jackie   11    manpada

In [47]:
df.drop(0,inplace = True)
df

     Name  Age     City
1    John   31  manpada
2  mayank   21   Bombay
3  jackie   11  manpada

In [50]:
df = pd.read_csv('sales_data.csv')
df

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal
2,10003,2024-01-03,Clothing,Levi's 501 Jeans,3,69.99,209.97,Asia,Debit Card
3,10004,2024-01-04,Books,The Da Vinci Code,4,15.99,63.96,North America,Credit Card
4,10005,2024-01-05,Beauty Products,Neutrogena Skincare Set,1,89.99,89.99,Europe,PayPal
...,...,...,...,...,...,...,...,...,...
235,10236,2024-08-23,Home Appliances,Nespresso Vertuo Next Coffee and Espresso Maker,1,159.99,159.99,Europe,PayPal
236,10237,2024-08-24,Clothing,Nike Air Force 1 Sneakers,3,90.00,270.00,Asia,Debit Card
237,10238,2024-08-25,Books,The Handmaid's Tale by Margaret Atwood,3,10.99,32.97,North America,Credit Card
238,10239,2024-08-26,Beauty Products,Sunday Riley Luna Sleeping Night Oil,1,55.00,55.00,Europe,PayPal
239,10240,2024-08-27,Sports,Yeti Rambler 20 oz Tumbler,2,29.99,59.98,Asia,Credit Card

In [55]:
#Display the daat types of each column
print("Data types:\n",df.dtypes)
print()
#Describe the DataFrame
print("Statistical summary:\n",df.describe())

Data types:
 Transaction ID        int64
Date                 object
Product Category     object
Product Name         object
Units Sold            int64
Unit Price          float64
Total Revenue       float64
Region               object
Payment Method       object
dtype: object

Statistical summary:
        Transaction ID  Units Sold   Unit Price  Total Revenue
count       240.00000  240.000000   240.000000     240.000000
mean      10120.50000    2.158333   236.395583     335.699375
std          69.42622    1.322454   429.446695     485.804469
min       10001.00000    1.000000     6.500000       6.500000
25%       10060.75000    1.000000    29.500000      62.965000
50%       10120.50000    2.000000    89.990000     179.970000
75%       10180.25000    3.000000   249.990000     399.225000
max       10240.00000   10.000000  3899.990000    3899.990000