## handling imbalanced dataset : 
-> if the dataset is not distributed properly the model prediction result maybe biased 

-> so to maintain the fairness we fix the dataset :
1. upsampling
2. downsampling

In [3]:
import numpy as np
import pandas as pd

# set the random seed for reproducibility
np.random.seed(123)

# create a dataframe with two classes
n_samples = 1000
class_0_ratio = 0.9
n_class_0 = int(n_samples * class_0_ratio)
n_class_1 = n_samples - n_class_0

In [4]:
n_class_0,n_class_1

(900, 100)

In [5]:
## CREATE MY DATAFRAME WITH IMBALANCED DATASET
class_0 = pd.DataFrame({
    'feature_1': np.random.normal(loc = 0, scale = 1, size = n_class_0),
    'feature_2': np.random.normal(loc = 0, scale = 1, size = n_class_0),
    'target' : [0]*n_class_0
})

class_1 = pd.DataFrame({
    'feature_1': np.random.normal(loc = 0, scale = 1, size = n_class_1),
    'feature_2': np.random.normal(loc = 0, scale = 1, size = n_class_1),
    'target' : [1]*n_class_1
})

In [6]:
class_0

     feature_1  feature_2  target
0    -1.085631   0.551302       0
1     0.997345   0.419589       0
2     0.282978   1.815652       0
3    -1.506295  -0.252750       0
4    -0.578600  -0.292004       0
..         ...        ...     ...
895   0.238761  -0.003155       0
896  -1.106386  -0.430660       0
897   0.366732  -0.146416       0
898   1.023906   1.160176       0
899  -0.210056  -0.641512       0

[900 rows x 3 columns]

In [7]:
class_1

    feature_1  feature_2  target
0   -0.300232   0.139033       1
1   -0.632261   0.025577       1
2   -0.204317  -0.196443       1
3    0.213696   1.312255       1
4    1.033878   1.187417       1
..        ...        ...     ...
95  -0.623629   0.845701       1
96   0.239810  -1.119923       1
97  -0.868240  -0.359297       1
98   0.902006  -1.609695       1
99   0.697490   0.013570       1

[100 rows x 3 columns]

In [8]:
df = pd.concat([class_0,class_1]).reset_index(drop = True)
df.head()

   feature_1  feature_2  target
0  -1.085631   0.551302       0
1   0.997345   0.419589       0
2   0.282978   1.815652       0
3  -1.506295  -0.252750       0
4  -0.578600  -0.292004       0

In [9]:
df.tail()

     feature_1  feature_2  target
995  -0.623629   0.845701       1
996   0.239810  -1.119923       1
997  -0.868240  -0.359297       1
998   0.902006  -1.609695       1
999   0.697490   0.013570       1

In [10]:
df['target'].value_counts()

target
0    900
1    100
Name: count, dtype: int64

In [11]:
## upsampling
df_minority = df[df['target'] == 1]
df_majority = df[df['target'] == 0]

In [12]:
from sklearn.utils import resample
df_minority_upsampled = resample(
            df_minority,replace=True, ## ssample with replacement
            n_samples = len(df_majority),
            random_state=42
         )

In [13]:
df_minority_upsampled.shape

(900, 3)

In [14]:
df_minority_upsampled.head()

     feature_1  feature_2  target
951  -0.874146  -0.156083       1
992   0.196570  -0.602575       1
914  -0.067830   0.998053       1
971   0.272825   1.034197       1
960   0.870056  -0.449515       1

In [15]:
df_upsampled = pd.concat([df_majority,df_minority_upsampled])

In [16]:
df_upsampled['target'].value_counts()

target
0    900
1    900
Name: count, dtype: int64

In [17]:
## downsampling

import numpy as np
import pandas as pd

# set the random seed for reproducibility
np.random.seed(123)

# create a dataframe with two classes
n_samples = 1000
class_0_ratio = 0.9
n_class_0 = int(n_samples * class_0_ratio)
n_class_1 = n_samples - n_class_0

## CREATE MY DATAFRAME WITH IMBALANCED DATASET
class_0 = pd.DataFrame({
    'feature_1': np.random.normal(loc = 0, scale = 1, size = n_class_0),
    'feature_2': np.random.normal(loc = 0, scale = 1, size = n_class_0),
    'target' : [0]*n_class_0
})

class_1 = pd.DataFrame({
    'feature_1': np.random.normal(loc = 0, scale = 1, size = n_class_1),
    'feature_2': np.random.normal(loc = 0, scale = 1, size = n_class_1),
    'target' : [1]*n_class_1
})
df = pd.concat([class_0,class_1]).reset_index(drop = True)

## check the class distribution

print(df['target'].value_counts())

target
0    900
1    100
Name: count, dtype: int64

In [19]:
## downsampling
df_minority = df[df['target'] == 1]
df_majority = df[df['target'] == 0]

from sklearn.utils import resample
df_majority_downsampled = resample(
            df_majority,replace=False, 
            n_samples = len(df_minority),
            random_state=42
         )

df_downsampled = pd.concat([df_minority,df_majority_downsampled])

In [20]:
df_downsampled.shape

(200, 3)

In [21]:
## downsampled is bad because we are losing data